language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/alarm/alarm.ino
    - PLATFORMIO_CI_SRC=examples/clock/clock.ino
    - PLATFORMIO_CI_SRC=examples/tm_format/tm_format.ino

install:
    - pip install -U platformio

script:
    - platformio ci --lib=. --board=megaatmega2560 --board uno
